title: Müllers Zorn
email: anfrage@kaspar-allenbach.ch
description: >- # this means to ignore newlines until "baseurl:"
  Gedichte des Seeländer Malers Erich Müler-Santis.
google_site_verification: ""
image: ""
author: ""
locale: ""
social:
  name: Ben Balter
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  gedichte:
    output: true
kramdown:
  hard_wrap: true

baseurl: "/muellers-zorn"
url: "https://kaspar-allenbach.github.io/muellers-zorn/"
environment: production
