title: Müllers Zorn
email: anfrage@kaspar-allenbach.ch
description: >- # this means to ignore newlines until "baseurl:"
  Gedichte des Seeländer Malers Erich Müler-Santis.
google_site_verification: "RTRb9-5C8Yd04clozDff3vc0cy32trkj3b20-wnEEfo"
image: ""
author: "Kaspar Allenbach"
locale: "de_ch"
social:
  name: Kaspar Allenbach
  links:
    - https://www.instagram.com/kasparallenbach/
    - https://www.threads.net/@kasparallenbachgithub
    - https://github.com/kaspar-allenbach
    - https://www.linkedin.com/in/kaspar-allenbach-138689248/

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  gedichte:
    output: true
kramdown:
  hard_wrap: true

baseurl: ""
url: "https://muellers-zorn.ch/"
environment: production
